=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/ch6/invitation.dtd
<!-- invitation DTD   -->
<!-- May 26th 1998 mg -->
<!ELEMENT invitation (front, body, back) >
<!ELEMENT front      (to, date, where, why?) >
<!ELEMENT date       (#PCDATA) >
<!ELEMENT to         (#PCDATA) >
<!ELEMENT where      (#PCDATA) >
<!ELEMENT why        (#PCDATA) >
<!ELEMENT body       (par+) >
<!ELEMENT par        (#PCDATA|emph)* >
<!ELEMENT emph       (#PCDATA) >
<!ELEMENT back       (signature) >
<!ELEMENT signature  (#PCDATA) >

=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/ch6/invitation.xml
<?xml version="1.0"?>
<!DOCTYPE invitation SYSTEM "invitation.dtd">
<invitation>
<!-- ++++ The header part of the document ++++ -->
<front>
<to>Anna, Bernard, Didier, Johanna</to>
<date>Next Friday Evening at 8 pm</date>
<where>The Web Cafe</where>
<why>My first XML baby</why>
</front>
<!-- +++++ The main part of the document +++++ -->
<body>
<par>
I would like to invite you all to celebrate
the birth of <emph>Invitation</emph>, my
first XML document child.
</par>
<par>
Please do your best to come and join me next Friday
evening. And, do not forget to bring your friends.
</par>
<par>
I <emph>really</emph> look forward to see you soon!
</par>
</body>
<!-- +++ The closing part of the document ++++ -->
<back>
<signature>Michel</signature>
</back>
</invitation>
