=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/apb/biblioxml1.dtd
<!-- biblioxml1.dtd: XML DTD for BibTeX markup: version 1 -->

<!-- Every biblio entry _must_ have an identifier and
                        _can_  have a cross-reference to an existing entry -->
<!ENTITY % atype  "id       ID    #REQUIRED 
                   crossref IDREF #IMPLIED">

<!-- Possible types of biblio entries -->
<!ELEMENT biblio (#PCDATA | article| book| booklet| inbook| incollection|
                            inproceedings| manual| mastersthesis| misc| 
                            phdthesis| proceedings| techreport| unpublished)*>

<!-- Optional annotation, note, ISBN, or key (the latter for sorting) -->
<!ENTITY % info "(annote|note|ISBN|key)*">

<!-- An article from a journal or magazine -->
<!ELEMENT article (author, title, journal, year, 
                   volume?, number?, pages?, month?, %info;)>
<!ATTLIST article %atype;>

<!-- A book with an explicit publisher -->
<!ELEMENT book ((author|editor), title, publisher, year,
                (volume|number)?, series?, address?, edition?, month?, %info;)>
<!ATTLIST book %atype;>

<!-- A work that is printed or bound, but without a named -->
<!--   publisher or sponsoring institution                -->
<!ELEMENT booklet (title , 
                   author, howpublished?, address?, month?, year?, %info;)>
<!ATTLIST booklet %atype;>

<!-- A part of a book, usually untitled;                       -->
<!--   (a chapter, a sectional unit, or just a range of pages) -->
<!ELEMENT inbook ((author|editor), title, (chapter|pages)*, publisher, year,
                  (volume|number)?, series?, type?, address?, edition?, month?, %info;)> 
<!ATTLIST inbook %atype;>

<!-- A part of a book with its own title -->
<!ELEMENT incollection (author, title, booktitle, publisher, year,
                        editor?, (volume|number)?, series?, type?, chapter?,
                        pages?, address?, edition?, month?, %info;)>
<!ATTLIST incollection %atype;>

<!-- An article in a conference proceedings -->
<!ELEMENT inproceedings (author, title, booktitle, year,
                         editor?, (volume|number)?, series?, pages?, address?,
                         month?, organization?, publisher?, %info;)>
<!ATTLIST inproceedings %atype;>

<!-- Technical documentation -->
<!ELEMENT manual (title,
                  author?, organization?, address?, edition?, month?, year?, %info;)>
<!ATTLIST manual %atype;>

<!-- A master's thesis -->
<!ELEMENT mastersthesis (author, title, school, year,
                         type?, address?, month?, %info;)>
<!ATTLIST mastersthesis %atype;>

<!-- Miscelleneous: use this type if nothing else fits -->
<!ELEMENT misc (author?, title?, howpublished?, month?, year?,%info;)>
<!ATTLIST misc %atype;>

<!-- A Ph. D. thesis -->
<!ELEMENT phdthesis (author, title, school, year,
                     type?, address?, month?, %info;)>
<!ATTLIST phdthesis %atype;>

<!-- The porceedings of a conference -->
<!ELEMENT proceedings (title  , year ,
                       editor?, (volume|number)?, series?, address?, 
                       month?, organization?, publisher?, %info;)>
<!ATTLIST proceedings %atype;>

<!-- A report published by a school or other institution -->
<!--   usually numbered within a series                  -->
<!ELEMENT techreport (author, title, institution, year,
                      type?, number?, address?, month?, %info;)>
<!ATTLIST techreport %atype;>

<!-- A document with author and title, but not formally published -->
<!ELEMENT unpublished (author, title, note,
                       month? , key?)>
<!ATTLIST unpublished %atype;>

<!-- For adding typographic emphasis to the information -->
<!ELEMENT emph (#PCDATA)>
<!ATTLIST emph style (textbf|emph|textsf|textsl|texttt|quote) "emph">

<!ENTITY % inline "(#PCDATA|emph)*">
<!-- The basic fields (Lamport (1994), pages 162-164) -->

             <!-- Usually the address of publisher or institution -->
<!ELEMENT address       (#PCDATA|emph)*>
             <!-- Annotation (not used by standard styles)        -->
<!ELEMENT annote        (#PCDATA|emph)*>
             <!-- Author(s) in format described on pp. 157-158    -->
<!ELEMENT author        (names)>
<!ELEMENT names         ((first,last),(and,first,last)*)>
<!ELEMENT last          (#PCDATA|emph)*>
<!ELEMENT first         (#PCDATA|emph)*>
<!ELEMENT and           EMPTY>
     <!-- Title of a book, used in incollection and inproceedings -->
<!ELEMENT booktitle     (#PCDATA|emph)*>
             <!-- Chapter (or sectional unit) number              -->
<!ELEMENT chapter       (#PCDATA|emph)*>
             <!-- Edition of a book (e.g., "third")               -->
<!ELEMENT edition       (#PCDATA|emph)*>
             <!-- Names of editor(s)                              -->
<!ELEMENT editor        (names)>
             <!-- Describe how something strange is published     -->
<!ELEMENT howpublished  (#PCDATA|emph)*>
             <!-- Sponsoring institution of a technical report    -->
<!ELEMENT institution   (#PCDATA|emph)*>
             <!-- The ISBN number (non-standard, but useful       -->
<!ELEMENT ISBN          (#PCDATA)>
             <!-- A journal's name                                -->
<!ELEMENT journal       (#PCDATA|emph)*>
             <!-- Used for ordering the biblio entries            -->
<!ELEMENT key           (#PCDATA)>
         <!-- Month of publication (or writing, if not published) -->
<!ELEMENT month         (#PCDATA)>
         <!-- Additional information to help the user             -->
<!ELEMENT note          (#PCDATA|emph)*>
         <!-- Number of a journal, magazine, report, etc.         -->
<!ELEMENT number        (#PCDATA)>
         <!-- Sponsor of conference or publisher of manual        -->
<!ELEMENT organization  (#PCDATA|emph)*>
         <!-- page, or page range                                 -->
<!ELEMENT pages         (#PCDATA)>
         <!-- Publisher's name                                    -->
<!ELEMENT publisher     (#PCDATA|emph)*>
         <!-- Name of the school where thesis was written         -->
<!ELEMENT school        (#PCDATA|emph)*>
         <!-- Name of the series or set of books                  -->
<!ELEMENT series        (#PCDATA|emph)*>
         <!-- A work's title                                      -->
<!ELEMENT title         (#PCDATA|emph)*>
         <!-- Type of a technical report, e.g., "Research Note"   -->
<!ELEMENT type          (#PCDATA|emph)*>
         <!-- Volume number of a journal or multi-volume book     -->
<!ELEMENT volume        (#PCDATA)>
         <!-- Year of publication (or writing, if not published)  -->
<!ELEMENT year          (#PCDATA)>

=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/apb/bibliotest1.xml
<!DOCTYPE biblio SYSTEM "biblioxml1.dtd" [
<!ENTITY AW "Addison-Wesley">
<!ENTITY AW:adr "Reading, Massachusetts">
<!ENTITY emdash "---">
<!ENTITY endash "--">
<!ENTITY ouml '\"o'>
<!ENTITY j-TUGboat "TUGboat">
<!ENTITY LaTeX "\LaTeX{}">
<!ENTITY TeX "\TeX{}">
<!ENTITY WEB "\textsc{web}">
<!-- abreviations for the months -->
<!ENTITY jan "Jan.">
<!ENTITY feb "Feb.">
<!ENTITY mar "Mar.">
<!ENTITY apr "Apr.">
<!ENTITY may "May">
<!ENTITY jun "Jun.">
<!ENTITY jul "Jul.">
<!ENTITY aug "Aug.">
<!ENTITY sep "Sep.">
<!ENTITY oct "Oct.">
<!ENTITY nov "Nov.">
<!ENTITY dec "Dec.">
]>
<biblio>
<manual id="Dynatext">
  <title>Dynatext, Electronic Book Indexer/Browser</title>
  <organization>Electronic Book Technology Inc.</organization>
  <address>Providence, Rhode Island</address>
  <year>1991</year>
</manual>
  <book id="Eijkhout:1991">
  <author><names><first>Victor</first><last>Eijkhout</last></names></author>
  <title>&TeX; by Topic, a &TeX;nicians Reference</title>
  <publisher>&AW;</publisher>
  <year>1991</year>
  <address>&AW:adr;</address>
</book>,
<techreport id="EVH:Office">
  <author><names><first>Eric</first><last>van Herwijnen</last></names></author>
  <title>Future Office Systems Requirements</title>
  <institution>CERN DD Internal Note</institution>
  <year>1988</year>
  <month>&nov;</month>
</techreport>
<article id="Felici:1991">
  <author><names><first>James</first><last>Felici</last></names></author>
  <title>PostScript versus TrueType</title>
  <journal>Macworld</journal>
  <year>1991</year>
  <volume>8</volume>
  <pages>195&endash;201</pages>
  <month>&sep;</month>
</article>
<techreport id="Knuth:WEB">
  <author><names><first>Donald E.</first><last>Knuth</last></names></author>
  <title>The &WEB; System of Structured Documentation</title>
  <institution>Department of Computer Science, Stanford University</institution>
  <year>1983</year>
  <number>STAN-CS-83-980</number>
  <address>Stanford, CA 94305</address>
  <month>&sep;</month> 
</techreport>
<phdthesis id="Liang:1983">
  <author><names><first>Franklin Mark</first><last>Liang</last></names></author>
  <title>Word Hy-phen-a-tion by Com-pu-ter</title>
  <school>Stanford University</school>
  <year>1983</year>
  <address>Stanford, CA 94305</address>
  <month>&jun;</month>
  <note>Also available as Stanford University, Department of 
    Computer Science Report No. STAN-CS-83-977</note>
</phdthesis>
<article id="Mittelbach-Schoepf:1990">
  <author><names><first>Frank</first><last>Mittelbach</last><and/>
          <first>Rainer</first><last>Sch&ouml;pf</last></names></author>
  <title>The New Font Selection &emdash; User Interface to 
     Standard &LaTeX;</title>
  <journal>&j-TUGboat;</journal>
  <year>1990</year>
  <volume>11</volume>
  <number>2</number>
  <pages>297&endash;305</pages>
</article>
<incollection id="Wood:color" crossref="Roth:postscript">
  <author><names><first>Pat</first><last>Wood</last></names></author>
  <title>PostScript Color Separation</title>
  <booktitle>Real World PostScript</booktitle>
  <publisher>&AW;</publisher>
  <year>1988</year>
  <pages>201&endash;225</pages>
</incollection>
<book id="Roth:postscript">
  <editor><names><first>Stephen E.</first><last>Roth</last></names></editor>
  <title>Real World PostScript</title>
  <publisher>&AW;</publisher>
  <year>1988</year>
  <address>&AW:adr;</address>
  <ISBN>0-201-06663-7</ISBN>
</book>
<inproceedings id="Yannis:1991">
  <author><names><first>Yannis</first><last>Haralambous</last></names></author>
  <title>&TeX; and those other languages</title>
  <booktitle>1991 Annual Meeting Proceedings, Part 2, &TeX; Users Group, 
           Twelfth Annual Meeting, Dedham, Massachusetts, July 15--18, 1991 
  </booktitle>
  <year>1991</year>
  <editor><names><first>Hope</first><last>Hamilton</last></names></editor>
  <volume>12</volume>
  <series>&j-TUGboat;</series>
  <pages>539&endash;548</pages>
  <address>Providence, Rhode Island</address>
  <month>&dec;</month>
  <organization>&TeX; Users Group</organization>
</inproceedings>
</biblio>
