=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/apb/minilatex.dtd
<!-- minilatex.dtd: XML version of a subset of LaTeX -->
<!-- Most elements have the following attributes  -->
<!ENTITY % all    "id    ID #IMPLIED
                   class CDATA #IMPLIED
                   style CDATA #IMPLIED">
<!-- Most non-empty elements have this language attribute -->
<!ENTITY % i18n   "xml:lang NMTOKEN #IMPLIED">
<!ENTITY % basic  "%all; %i18n;">
<!-- Declaration of parameter entities for structuring the DTD -->
<!ENTITY % fontchange.new "">
<!ENTITY % fontchange "emph|textbf|textsc|textsf|textsl|texttt %fontchange.new;">
<!ENTITY % misc.new "">
<!ENTITY % misc "url|quad|hspace|vspace|includegraphics|tag|ent %misc.new;">
<!ENTITY % xref.new  "">
<!ENTITY % xref "cite|pageref|ref %xref.new;">
<!ENTITY % mathobj.new "">
<!ENTITY % mathobj "displaymath|inlinemath|equation|eqnarray" > 
<!ENTITY % inline.new "">
<!ENTITY % inline  "%fontchange;|quote|tabular|%misc;|%xref;|%mathobj; %inline.new;">
<!ENTITY % list.new "">
<!ENTITY % list    "lalist|description|enumerate|itemize|bibliography %list.new;">
<!ENTITY % preformat.new "">
<!ENTITY % preformat "verbatim|verse %preformat.new;">
<!ENTITY % likepara.new "">
<!ENTITY % likepara "%list;|quotation|align|%preformat; %likepara.new;">
<!ENTITY % floats.new "">
<!ENTITY % floats "figure|table %floats.new;">

<!-- The top level document declarations                     -->
<!ELEMENT document (frontmatter?,bodymatter,backmatter?)>
<!ATTLIST document %i18n; 
                   class CDATA "article">
<!ELEMENT frontmatter (title,author?,date?,abstract?,keywords?)>
<!ELEMENT bodymatter  ((par|%likepara;|%floats;|part|chapter|section)*,appendix*)>
<!ELEMENT backmatter  (index|glossary)*>
<!-- fontchanges -->
<!ELEMENT emph    (#PCDATA|%inline;)*>
<!ELEMENT textbf  (#PCDATA|%inline;)*>
<!ELEMENT textsc  (#PCDATA|%inline;)*>
<!ELEMENT textsf  (#PCDATA|%inline;)*>
<!ELEMENT textsl  (#PCDATA|%inline;)*>
<!ELEMENT texttt  (#PCDATA|%inline;)*>
<!-- cross-references -->
<!ENTITY % idref  "refid IDREF #REQUIRED">
<!ELEMENT cite     EMPTY>
<!ATTLIST cite     %idref;>
<!ELEMENT pageref  EMPTY>
<!ATTLIST pageref  %idref;>
<!ELEMENT ref      EMPTY>
<!ATTLIST ref      %idref;>
<!-- quoted material inline and displayed -->
<!ELEMENT quote        (#PCDATA|%inline;|par)*>
<!ATTLIST quote        %basic;>
<!ELEMENT quotation    (#PCDATA|%inline;|par)*>
<!ATTLIST quotation    %basic;>
<!-- lists -->
<!ELEMENT description  ((term*,item*)+)>
<!ELEMENT enumerate    ((term*,item*)+)>
<!ATTLIST enumerate    %basic;>
<!ELEMENT itemize      ((term*,item*)+)>
<!ATTLIST itemize      %basic;>
<!ELEMENT lalist       ((term*,item*)+)>
<!ATTLIST lalist       %basic;>
<!ELEMENT term         (#PCDATA|%inline;)*>
<!ATTLIST term         %basic;>
<!ELEMENT item         (#PCDATA|%inline;|par|%likepara;)*>
<!ATTLIST item         %basic;>
<!ELEMENT bibliography (bibitem)*>
<!ATTLIST bibliography %basic;>
<!ELEMENT bibitem      (#PCDATA|%inline;|par|%likepara;)*>
<!ATTLIST bibitem      %basic;>
<!-- low-level bits and pieces -->
<!ELEMENT url    EMPTY>
<!ATTLIST url    name CDATA #REQUIRED>
<!ELEMENT quad   EMPTY>
<!ELEMENT hspace EMPTY>
<!ATTLIST hspace dim CDATA #REQUIRED>
<!ELEMENT vspace EMPTY>
<!ATTLIST vspace dim CDATA #REQUIRED>
<!ELEMENT tag    (#PCDATA)>
<!ELEMENT ent    EMPTY>
<!ATTLIST ent    value CDATA #REQUIRED
                 name  CDATA #REQUIRED>
<!-- everything that can go into a paragraph -->
<!ELEMENT par     (#PCDATA|%inline;|%likepara;)*>
<!ATTLIST par     %basic;>
<!-- "floats" and their contents -->
<!ELEMENT figure  (#PCDATA|par|%inline;|%likepara;|includegraphics|caption)*>
<!ATTLIST figure  %basic;>
<!ELEMENT table   (#PCDATA|par|%inline;|%likepara;|tabular|caption)*>
<!ATTLIST table   %basic;>
<!ELEMENT includegraphics EMPTY>
<!ATTLIST includegraphics %basic;
                          file     CDATA #REQUIRED
                          width    CDATA #IMPLIED
                          height   CDATA #IMPLIED
                          bb       CDATA #IMPLIED
                          scale    CDATA ".5"
                          angle    CDATA #IMPLIED>
<!ELEMENT caption  (#PCDATA|par|%inline;)*>
<!ATTLIST caption  %basic;>
<!-- tabular material -->
<!ELEMENT tabular (hline|row)*>
<!ATTLIST tabular %basic;
                  preamble CDATA  #REQUIRED
                  width    CDATA  #IMPLIED 
                  border   CDATA  #IMPLIED>
<!ELEMENT row     (cell)*>
<!ATTLIST row     %basic;>
<!ELEMENT hline   EMPTY>
<!ELEMENT cell    (#PCDATA|%inline;)*>
<!ATTLIST cell    %basic;
                  rowspan CDATA "1"
                  colspan CDATA "1"
                  align   (left|center|right) "center">
<!-- verbatim material -->
<!ELEMENT verbatim (#PCDATA)>
<!ATTLIST verbatim %basic;
                   xml:space (default|preserve) 'preserve'>
<!ELEMENT verse    (#PCDATA|%inline;)*>
<!ATTLIST verse    %basic;
                   xml:space (default|preserve) 'preserve'>
<!-- things that go in the frontmatter -->
<!ELEMENT newline  EMPTY>
<!ELEMENT title    (#PCDATA|%inline;|thanks|newline)*>
<!ATTLIST title    %basic;>
<!ELEMENT author   (#PCDATA|%inline;|name|thanks|inst)*>
<!ELEMENT name     (#PCDATA|%inline;)*>
<!ATTLIST name     %basic;>
<!ELEMENT thanks   (#PCDATA|%inline;|newline)*>
<!ATTLIST thanks   %basic;>
<!ELEMENT inst     (#PCDATA|%inline;|newline)*>
<!ATTLIST inst     %basic;>
<!ELEMENT date     (#PCDATA)>
<!ATTLIST date     %basic;>
<!ELEMENT abstract (par+)>
<!ATTLIST abstract %basic;>
<!-- structuring -->
<!ENTITY % sect          "stitle, (par|%likepara;|%floats;)* ">
<!ELEMENT stitle         (#PCDATA|%inline;)*>
<!ATTLIST stitle          %basic;>
<!ELEMENT part           (%sect;, (chapter|section|subsection|subsubsection)*)>
<!ATTLIST part            %basic;>
<!ELEMENT chapter        (%sect;, section*)> 
<!ATTLIST chapter         %basic;>
<!ELEMENT section        (%sect;, subsection*)>
<!ATTLIST section         %basic;>
<!ELEMENT subsection     (%sect;, subsubsection*)>
<!ATTLIST subsection      %basic;>
<!ELEMENT subsubsection  (%sect;, paragraph*)>
<!ATTLIST subsubsection   %basic;>
<!ELEMENT paragraph      (%sect;, subparagraph*)>
<!ATTLIST paragraph       %basic;>
<!ELEMENT subparagraph   (%sect;)>
<!ATTLIST subparagraph    %basic;>
<!ELEMENT appendix       EMPTY>
<!-- backmatter: index and glossary -->
<!ELEMENT index (par|%likepara;)*>
<!ATTLIST index %basic;>
<!ELEMENT glossary (par|%likepara;)*>
<!ATTLIST glossagry %basic;>
<!-- LaTeX math constructs -->
<!ENTITY % LaTeXmath  "INCLUDE">
<!ENTITY % latexmath.dtd SYSTEM "latexmath.dtd">
<![ %LaTeXmath; [
%latexmath.dtd;
]]>
<!ENTITY % MathML     "IGNORE">
<!ENTITY % latexmml.dtd SYSTEM "latexmml.dtd">
<![ %MathML; [
%latexmml.dtd;
]]>
<!-- Basic XML entities -->
<!ENTITY lt     "&#60;"> <!-- "<" -->
<!ENTITY gt     "&#62;"> <!-- ">" -->
<!ENTITY amp    "&#38;"> <!-- "&" -->
<!ENTITY apos   "&#39;"> <!-- "'" -->
<!ENTITY quot   "&#34;"> <!-- '"' -->

=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/apb/minilatexexa.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE document SYSTEM "minilatex.dtd"[
<!ENTITY LaTeX  "\LaTeX{}">
<!ENTITY TeX    "\TeX{}">
<!ENTITY dots   "\dots">
<!ENTITY endash "--">
<!ENTITY emdash "---">
<!ENTITY nbsp   "~">
<!ENTITY % inline.new "|footnote">
<!ELEMENT footnote (#PCDATA|par)*>
]>
<document class="article" xml:lang="en">
<frontmatter>
<title>The &LaTeX; DTD and multiple languages</title>
<author><name>Michel Goossens</name>
<thanks>Partly from an example in <emph>The &LaTeX; Companion</emph>
</thanks></author>
<date>August 4th, 1998</date>
</frontmatter>
<bodymatter>
<section id="sec-en">
<stitle>The basic principles</stitle>
<par>
This is an example input file. We start in English to show the
principle. You should especially pay attention that we have used
slightly different notation for some of the common &LaTeX; constructs,
such as the dashes, which come in three sizes: an intra-word dash, a
medium dash for number ranges like 1&endash;2, and a punctuation
dash&emdash;like this.  Text can be emphasized as <emph>shown
here</emph>. An ellipsis is made with &dots; Footnotes<footnote>This
is a simple footnote.<par>It can also contain <texttt>par</texttt>
elements.</par></footnote> are tricky constructs, since one must be
careful not to nest them.
</par>
<subsection>
<stitle>Dealing with special characters</stitle>
<par>
XML has a different set of reserved characters than &LaTeX;, in
particular, when you want to use any of the three characters
<texttt><![CDATA[\&]]></texttt>, <texttt><![CDATA[<]]></texttt>, 
and <texttt><![CDATA[>]]></texttt>, you should enter them as
<texttt>\&amp;amp;</texttt>, <texttt>\&amp;lt;</texttt>, and
<texttt>\&amp;gt;</texttt>, respectively.
</par>
</subsection>
<subsection id="sec-math">
<stitle>&LaTeX; and mathematical formulae</stitle>
<par>
&LaTeX; and <emph>a fortiori</emph> &TeX; are very good at typesetting
mathematical formulae, like 
<inlinemath><![CDATA[x- 3 y + z < 7]]></inlinemath> or 
<inlinemath><![CDATA[a_{1} > x^{2n} + y^{2n} > x']]></inlinemath> or 
<inlinemath><![CDATA[(A, B) = \sum_{i} a_{i} b_{i}]]></inlinemath>.
Do not forget that for reasons of consistency, if you want to refer to
a variable in one of the formulae, such as the symbol 
<inlinemath>x</inlinemath>, you must also use math mode in the text.
</par>
</subsection>
</section>
<section xml:lang="de">
<stitle>Beispiel eines Textes in deutscher Sprache</stitle>
<subsection>
<stitle>Eine EPS Abbildung</stitle>
<par>
Dieser Abschnitt zeigt, wie man eine PostScript-Abbildung
<cite refid="bib-PS"/> in ein Dokument einbinden kann.  
Abbildung&nbsp;<ref refid="fig-psfig"/> wurde mit dem Befehl 
<verbatim>
<![CDATA[\includegraphics[width="3cm"]{file="colorcir.eps}]]>
</verbatim>
in den Text aufgenommen.
</par>
<figure id="fig-psfig">
<includegraphics width="3cm" file="colorcir.eps"/>
<caption xml:lang="de">Ein EPS Bild</caption>
</figure>
</subsection>
<subsection>
<stitle>Beispiel einer Tabelle</stitle> 
<par>Die Tabelle&nbsp;<ref refid="tab-exag"/> auf Seite&nbsp;<pageref
refid="tab-exag"/> zeigt eine Tabelle.
</par>
<table id="tab-exag">
<caption xml:lang="de">
Eingabe der deutschen Zusatzzeichen in &LaTeX;</caption>
<tabular preamble="ccccccc">
<row>
<cell><texttt>&#34;a</texttt>&nbsp;ä</cell>
<cell><texttt>&#34;A</texttt>&nbsp;Ä</cell>
<cell><texttt>&#34;o</texttt>&nbsp;ö</cell>
<cell><texttt>&#34;O</texttt>&nbsp;Ö</cell>
<cell><texttt>&#34;u</texttt>&nbsp;ü</cell>
<cell><texttt>&#34;U</texttt>&nbsp;Ü</cell>
<cell><texttt>&#34;s</texttt>&nbsp;&#223;</cell>
</row>
</tabular>
</table>
</subsection>
</section>
<section xml:lang="fr">
<stitle>Continuation du texte en français</stitle>
<subsection id="sec-list">
<stitle>Traiter les listes</stitle>
<par>
Les listes sont utilisées fréquemment pour structurer ou mettre
en évidence certains éléments d'un document (voir <cite refid="bib-Liste"/>).
</par>
<itemize>
  <item>Ceci est le premier élément d'une liste non-ordonnée. Chaque élément
    de ce type de liste est précédé d'un signe distinctif, comme une
    puce, un tiret, etc.
  </item>
  <item>Ce second élément de la même liste contient une liste de
    <emph>description</emph> imbriquée.
    <description>
      <term>XML</term>
      <item>Meta langage pour définir des classes de documents</item>
      <term>XLL</term>
      <item>Langage pour définir des hyperliens entre différentes
      parties de documents XML</item>
    </description>
    Nous continuons notre texte à l'intérieur de la première liste.
  </item>
</itemize>
</subsection>
</section>
<bibliography>
<bibitem id="bib-PS" xml:lang="de">
Adobe Inc. <emph>PostScript Handbuch (2. Auflage)</emph>
           Addison-Wesley (Deutschland) GmbH, Bonn, 1991.
</bibitem>
<bibitem id="bib-Liste" xml:lang="fr">
Michel Goossens. Personnaliser les listes &LaTeX;.
           <emph>Cahiers GUTenberg</emph>, 17:32&endash;48, mai 1994.
</bibitem>
</bibliography>
</bodymatter>
</document>
