=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/apc/invitationfr.dtd
<?xml version='1.0' encoding="ISO-8859-1"?>
<!-- DTD invitation (version française) -->
<!-- 11 novembre 1998 mg -->
<!ELEMENT invitation (entête, corps, fin) >
<!ELEMENT entête     (à, date, où, pourquoi?) >
<!ELEMENT date       (#PCDATA) >
<!ELEMENT à          (#PCDATA) >
<!ELEMENT où         (#PCDATA) >
<!ELEMENT pourquoi   (#PCDATA) >
<!ELEMENT corps      (par+) >
<!ELEMENT par        (#PCDATA|emph)* >
<!ELEMENT emph       (#PCDATA) >
<!ELEMENT fin        (signature) >
<!ELEMENT signature  (#PCDATA) >

=== Komorebi-yaodong/texlive-lang/texmf-dist/doc/latex/latex-web-companion/apc/invitationfr.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE invitation SYSTEM "invitationfr.dtd">
<invitation>
<!-- ++++ Partie entête ++++ -->
<entête>
<à>Anna, Bernard, Didier, Johanna</à>
<date>Vendredi prochain à 20 heures</date>
<où>Le Café du Web</où>
<pourquoi>Mon premier bébé XML</pourquoi>
</entête>
<!-- ++++ Partie corps  ++++ -->
<corps>
<par>
J'ai le plaisir de vous inviter à la célébration
de la naissance d'<emph>Invitation</emph>, mon
premier enfant document XML.
</par>
<par>
S'il vous plaît, faites tout votre possible pour me rejoindre 
vendredi prochain. Et n'oubliez pas d'emmener vos amis.
</par>
<par>
Je me réjouis <emph>vraiment</emph> d'avance de votre présence.
</par>
</corps>
<!-- ++++ Partie finale  ++++ -->
<fin>
<signature>Michel</signature>
</fin>
</invitation>
